# Generated by Django 3.2 on 2021-04-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='end_date',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='end_date',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='start_date',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Start date'),
        ),
    ]
